<a href="https://colab.research.google.com/github/filnels/Homeworks/blob/main/Numpy_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import library
import numpy as np

from numpy import pi

In [ ]:
a =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype='str', delimiter=',')

In [ ]:
# 1) Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [ ]:
 #print(a)

In [ ]:
target_column_index = 4

In [ ]:
a_without_target = np.delete(a, target_column_index, axis =1 )

In [ ]:
print(a_without_target)

In [ ]:
a_without_target=a_without_target.astype('float')

In [ ]:
print(a_without_target)



In [ ]:
# 2) Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [ ]:
print('Массив a_without_target 2D массив:', a_without_target.ndim == 2)

Массив a_without_target 2D массив: True


In [ ]:
# 3) Порахувати mean, median, standard deviation для 1-ї колонки

In [ ]:
first_column = a_without_target[:, 0]

In [ ]:
mean_value = round(np.mean(first_column),2)
median_value = round(np.median(first_column),2)
std_deviation = round(np.std(first_column),2)

In [ ]:
print('Mean першої колонки:', mean_value)
print('Median першої колонки:', median_value)
print('Std першої колонки:', std_deviation)

Mean першої колонки: 5.84
Median першої колонки: 5.8
Std першої колонки: 0.83


In [ ]:
# 4) Вставити 20 значень np.nan на випадкові позиції в масиві
# (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [ ]:
num_rows, num_cols = a_without_target.shape

print(num_rows, num_cols)

150 4


In [ ]:
random_indices = np.random.choice(num_rows*num_cols, size=20, replace=False)
print(random_indices)

[584 180 371 211 197 212 579 479  56 364 316 164 230 510 269 372 588 284
 520 351]


In [ ]:
row_indices, col_indices = np.unravel_index(random_indices, (num_rows, num_cols))
print(row_indices, col_indices)

[146  45  92  52  49  53 144 119  14  91  79  41  57 127  67  93 147  71
 130  87] [0 0 3 3 1 0 3 3 0 0 0 0 2 2 1 0 0 0 0 3]


In [ ]:
a_without_target[row_indices, col_indices] = np.nan

In [ ]:
print("Массив данных с 20 случайными значениями np.nan:\n", a_without_target )
print(' Количество Nan в массиве:\n', np.isnan(a_without_target).sum())

Массив данных с 20 случайными значениями np.nan:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [nan 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [nan 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [nan 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  nan 1.4 0.2]


In [ ]:
# 5) Знайти позиції вставлених значень np.nan в 1-й колонці

In [ ]:
first_column = a_without_target[:,0]
#print(first_column)

In [ ]:
nan_positions_first_column = np.where(np.isnan(first_column))

In [ ]:
print('Позиції вставлених значень np.nan в 1-й колонці', nan_positions_first_column)

Позиції вставлених значень np.nan в 1-й колонці (array([ 14,  41,  45,  53,  71,  79,  91,  93, 130, 146, 147], dtype=int64),)


In [ ]:
# 6)  Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [ ]:
filter = (a_without_target[:, 2] > 1.5) & (a_without_target[:, 0] < 5.0)
#print(filter)

In [ ]:
filtered_a_without_target = a_without_target[filter]

print("Отфильтрованный массив:\n", filtered_a_without_target )

Отфильтрованный массив:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.5 4.5 1.7]]


In [ ]:
# 7) Замінити всі значення np.nan на 0
a_without_target = np.nan_to_num(a_without_target, nan=0.0)
print('Массив с измененными значениями Nan на 0: \n', a_without_target)


Массив с измененными значениями Nan на 0: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [0.  4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [0.  2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [0.  3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  0.  1.4 0.2]
 [7.  

In [ ]:
# 8) Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [ ]:
uniqs, counts = np.unique(a_without_target, return_counts=True)
print('Unique items : ', uniqs)
print('Counts       : ', counts)

Unique items :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.6
 7.7 7.9]
Counts       :  [20  6 28  7  7  1  1  8  4  6 19 20 24 11  6 12  7  7  6  6 12  6 10  5
  8 14 10 27 12 13  6 12  8  4  4  7  5  6  4  5  3  8  8  7  7  8 10 13
 17  6  3  8  9 12 10  9  5  8  7  4  9  8  4  3 10  3  5  1  1  3  1  1
  4  1]


In [ ]:
# 8) Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [ ]:
a_left =a_without_target[:, :2]  # Перші 2 колонки
a_right = a_without_target[:, 2:4] # Наступні 2 колонки

In [ ]:
print('Перші 2 колонки\n', a_left)
print('Наступні 2 колонки\n', a_right)

Перші 2 колонки
 [[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [5.  3.4]
 [4.4 2.9]
 [4.9 3.1]
 [5.4 3.7]
 [4.8 3.4]
 [4.8 3. ]
 [4.3 3. ]
 [0.  4. ]
 [5.7 4.4]
 [5.4 3.9]
 [5.1 3.5]
 [5.7 3.8]
 [5.1 3.8]
 [5.4 3.4]
 [5.1 3.7]
 [4.6 3.6]
 [5.1 3.3]
 [4.8 3.4]
 [5.  3. ]
 [5.  3.4]
 [5.2 3.5]
 [5.2 3.4]
 [4.7 3.2]
 [4.8 3.1]
 [5.4 3.4]
 [5.2 4.1]
 [5.5 4.2]
 [4.9 3.1]
 [5.  3.2]
 [5.5 3.5]
 [4.9 3.1]
 [4.4 3. ]
 [5.1 3.4]
 [5.  3.5]
 [0.  2.3]
 [4.4 3.2]
 [5.  3.5]
 [5.1 3.8]
 [0.  3. ]
 [5.1 3.8]
 [4.6 3.2]
 [5.3 3.7]
 [5.  0. ]
 [7.  3.2]
 [6.4 3.2]
 [6.9 3.1]
 [0.  2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [4.9 2.4]
 [6.6 2.9]
 [5.2 2.7]
 [5.  2. ]
 [5.9 3. ]
 [6.  2.2]
 [6.1 2.9]
 [5.6 2.9]
 [6.7 3.1]
 [5.6 3. ]
 [5.8 0. ]
 [6.2 2.2]
 [5.6 2.5]
 [5.9 3.2]
 [0.  2.8]
 [6.3 2.5]
 [6.1 2.8]
 [6.4 2.9]
 [6.6 3. ]
 [6.8 2.8]
 [6.7 3. ]
 [6.  2.9]
 [0.  2.6]
 [5.5 2.4]
 [5.5 2.4]
 [5.8 2.7]
 [6.  2.7]
 [5.4 3. ]
 [6.  3.4]
 [6.7 3.1]
 [6.3 2.3]
 [5.6 3. ]
 [5.

In [ ]:
# 10) Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [ ]:
a_left_sorted = a_left[a_left[:, 0].argsort()]
a_right_sorted = a_right[a_right[:, 0].argsort()[::-1]]

In [ ]:
print('отсортированный первый массив по возрастанию, первая колонка\n', a_left_sorted )
print('отсортированный второй массив по убыванию, первая колонка\n', a_right_sorted )

отсортированный первый массив по возрастанию, первая колонка
 [[0.  2.8]
 [0.  3. ]
 [0.  3. ]
 [0.  2.5]
 [0.  2.6]
 [0.  2.3]
 [0.  2.3]
 [0.  2.8]
 [0.  2.3]
 [0.  3. ]
 [0.  4. ]
 [4.3 3. ]
 [4.4 3. ]
 [4.4 3.2]
 [4.4 2.9]
 [4.6 3.1]
 [4.6 3.2]
 [4.6 3.6]
 [4.6 3.4]
 [4.7 3.2]
 [4.7 3.2]
 [4.8 3.1]
 [4.8 3. ]
 [4.8 3.4]
 [4.8 3.4]
 [4.9 3. ]
 [4.9 2.4]
 [4.9 3.1]
 [4.9 2.5]
 [4.9 3.1]
 [4.9 3.1]
 [5.  3. ]
 [5.  3.5]
 [5.  3.2]
 [5.  3.5]
 [5.  0. ]
 [5.  2. ]
 [5.  3.6]
 [5.  3.4]
 [5.  3.4]
 [5.1 2.5]
 [5.1 3.8]
 [5.1 3.8]
 [5.1 3.5]
 [5.1 3.4]
 [5.1 3.5]
 [5.1 3.3]
 [5.1 3.7]
 [5.1 3.8]
 [5.2 4.1]
 [5.2 3.4]
 [5.2 3.5]
 [5.2 2.7]
 [5.3 3.7]
 [5.4 3.9]
 [5.4 3.7]
 [5.4 3.9]
 [5.4 3. ]
 [5.4 3.4]
 [5.4 3.4]
 [5.5 2.4]
 [5.5 2.4]
 [5.5 3.5]
 [5.5 2.5]
 [5.5 2.6]
 [5.5 4.2]
 [5.6 2.7]
 [5.6 2.5]
 [5.6 2.9]
 [5.6 3. ]
 [5.6 3. ]
 [5.6 2.8]
 [5.7 2.9]
 [5.7 3. ]
 [5.7 2.8]
 [5.7 4.4]
 [5.7 3.8]
 [5.7 2.5]
 [5.7 2.8]
 [5.8 0. ]
 [5.8 2.6]
 [5.8 2.7]
 [5.8 2.7]
 [5.8 2.7]
 [5.8 2.8]
 [5

In [ ]:
# 11) Зібрати обидва массиви в одне ціле

In [ ]:
a_combined = np.hstack((a_left_sorted, a_right_sorted))

In [ ]:
print('Объединенные массивы', a_combined)

Объединенные массивы [[0.  2.8 6.9 2.3]
 [0.  3.  6.7 2.2]
 [0.  3.  6.7 2. ]
 [0.  2.5 6.6 2.1]
 [0.  2.6 6.4 2. ]
 [0.  2.3 6.3 1.8]
 [0.  2.3 6.1 2.5]
 [0.  2.8 6.1 1.9]
 [0.  2.3 6.1 2.3]
 [0.  3.  6.  1.8]
 [0.  4.  6.  2.5]
 [4.3 3.  5.9 2.1]
 [4.4 3.  5.9 2.3]
 [4.4 3.2 5.8 2.2]
 [4.4 2.9 5.8 1.6]
 [4.6 3.1 5.8 1.8]
 [4.6 3.2 5.7 2.1]
 [4.6 3.6 5.7 2.3]
 [4.6 3.4 5.7 0. ]
 [4.7 3.2 5.6 2.2]
 [4.7 3.2 5.6 1.4]
 [4.8 3.1 5.6 2.4]
 [4.8 3.  5.6 2.1]
 [4.8 3.4 5.6 1.8]
 [4.8 3.4 5.6 2.4]
 [4.9 3.  5.5 1.8]
 [4.9 2.4 5.5 2.1]
 [4.9 3.1 5.5 1.8]
 [4.9 2.5 5.4 2.1]
 [4.9 3.1 5.4 2.3]
 [4.9 3.1 5.3 1.9]
 [5.  3.  5.3 2.3]
 [5.  3.5 5.2 2.3]
 [5.  3.2 5.2 2. ]
 [5.  3.5 5.1 1.9]
 [5.  0.  5.1 1.6]
 [5.  2.  5.1 2. ]
 [5.  3.6 5.1 1.8]
 [5.  3.4 5.1 1.5]
 [5.  3.4 5.1 2.4]
 [5.1 2.5 5.1 1.9]
 [5.1 3.8 5.1 2.3]
 [5.1 3.8 5.  0. ]
 [5.1 3.5 5.  1.7]
 [5.1 3.4 5.  1.9]
 [5.1 3.5 5.  2. ]
 [5.1 3.3 4.9 0. ]
 [5.1 3.7 4.9 2. ]
 [5.1 3.8 4.9 1.8]
 [5.2 4.1 4.9 1.5]
 [5.2 3.4 4.8 1.8]
 [5.2 3.5 

In [ ]:
# 12) Знайти найбільш часто повторюване значення в массиві

In [ ]:
uniqs, counts = np.unique(a_combined, return_counts=True)
most_frequent_index = np.argmax(counts)
most_frequent_value = uniqs[most_frequent_index]
print('найбільш часто повторюване значення в массиві : ', most_frequent_value)


найбільш часто повторюване значення в массиві :  0.2


In [ ]:
# 13) Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [ ]:
def modify_column(array):
    mean_value = np.mean(array)
    modified_array = np.where(array < mean_value, array * 2, array / 4)
    return modified_array



In [ ]:
# Застосувати отриману функцію до 3-ї колонки

In [ ]:
modified_column = modify_column(a_combined[:,2])
print("Модифікована колонка:", modified_column)

Модифікована колонка: [1.725 1.675 1.675 1.65  1.6   1.575 1.525 1.525 1.525 1.5   1.5   1.475
 1.475 1.45  1.45  1.45  1.425 1.425 1.425 1.4   1.4   1.4   1.4   1.4
 1.4   1.375 1.375 1.375 1.35  1.35  1.325 1.325 1.3   1.3   1.275 1.275
 1.275 1.275 1.275 1.275 1.275 1.275 1.25  1.25  1.25  1.25  1.225 1.225
 1.225 1.225 1.2   1.2   1.2   1.2   1.175 1.175 1.175 1.175 1.175 1.15
 1.15  1.15  1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.1   1.1
 1.1   1.1   1.075 1.075 1.05  1.05  1.05  1.05  1.025 1.025 1.025 1.
 1.    1.    1.    1.    0.975 0.975 0.975 0.95  7.4   7.2   7.    7.
 6.6   6.    3.8   3.8   3.4   3.4   3.4   3.4   3.2   3.2   3.2   3.2
 3.2   3.2   3.2   3.    3.    3.    3.    3.    3.    3.    3.    3.
 3.    3.    3.    3.    3.    2.8   2.8   2.8   2.8   2.8   2.8   2.8
 2.8   2.8   2.8   2.8   2.8   2.6   2.6   2.6   2.6   2.6   2.6   2.6
 2.4   2.4   2.2   2.    0.    0.   ]
